### ISSUE TITLE
Fehler "Comparison method violates its general contract!"

### ISSUE THREAD

**Issue by ghbw** [GollmerSt/TimerImportTool#2]
Hi,
dieser Fehler kommt gelegentlich hoch:
java.lang.IllegalArgumentException: Comparison method violates its general contract!
  at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
  at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
  at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
  at java.base/java.util.TimSort.sort(TimSort.java:245)
  at java.base/java.util.Arrays.sort(Arrays.java:1441)
  at dvbviewertimerimport.gui.TimersTreeTableModel.updateRoot(TimersTreeTableModel.java:78)
  at dvbviewertimerimport.gui.TimersDialog$MyTreeTable.<init>(TimersDialog.java:76)
  at dvbviewertimerimport.gui.TimersDialog.init(TimersDialog.java:170)
  at dvbviewertimerimport.DVBViewerTimerImport$1.actionPerformed(DVBViewerTimerImport.java:695)
  at tvbrowser/tvbrowser.core.plugin.ActionProxy.actionPerformed(ActionProxy.java:83)
  at tvbrowser/tvbrowser.ui.mainframe.toolbar.ToolBar.lambda$addButtonProperties$4(ToolBar.java:602)
  at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
  at tvbrowser/util.ui.PopupButton.fireActionPerformed(PopupButton.java:53)
  at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
  at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
  at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
  at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
  at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
  at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
  at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
  at java.desktop/java.awt.Component.processEvent(Component.java:6400)
  at java.desktop/java.awt.Container.processEvent(Container.java:2263)
  at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
  at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
  at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
  at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
  at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
  at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
  at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
  at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
  at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
  at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
  at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
  at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
  at java.base/java.security.AccessController.doPrivileged(Native Method)
  at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
  at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
  at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
  at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
  at java.base/java.security.AccessController.doPrivileged(Native Method)
  at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
  at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
  at tvbrowser/util.ui.textcomponentpopup.TextComponentPopupEventQueue.dispatchEvent(TextComponentPopupEventQueue.java:55)
  at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
  at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
  at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
  at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
  at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
  at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

VG

**Comment by GollmerSt** [comment]
Hallo,
weißt Du etwa, in welchem Zusammenhang der Fehler auftritt?

Ich habe mir mal den Code angesehen und kann noch keine direkte Ursache erkennen. Als einzige Möglichkeit sehe ich da ein Multithread-Problem, bei dem während eines Sortiervorgangs ein anderer Thread die zu sortierenden Daten modifiziert.

Aktuell sehe ich da aber kein solches Problem, bzw. evtl. etwas, das mit dem TV-Browser zusammen hängt.

Eh ich ich hier aber noch länger analysiere, dazu folgende Frage:

Soweit ich erkenne, musst Du die Übersicht mit den geplanten Aufnahmen (Timer-Verwaltung) geöffnet haben oder gerade öffnen bzw. den "Neu laden"-Button gedrückt haben. Als möglichen davon unabhängigen Thread erscheint mit da nur der TVBrowser selber in Frage kommen. War da evtl. ein Update der Sendungen noch nicht komplett abgeschlossen? Das läuft beim TV-Browser im Hintergrund und könnte durchaus zu einem solchen Fehler führen.

Soweit ich es noch in Erinnerung habe, bewirkt ein solche TV-Browser-Update, dass bei Sendungsänderungen, die Änderungen analysiert werden und entsprechend auch programmierte Timer an die neuen Zeiten angepasst werden. Das war damals ein etwas komplizierterer Algorithmus und funktioniert nicht immer (nur wenn neue Startzeit innerhalb der alten Sendung, was aber meist zutreffend ist).

Bevor ich mir diesen Teil mal genauer ansehe, könnte dieser im Hintergrund laufende TV-Browser-Update die Ursache darstellen?

Aktuell programmiere ich das Teil so gut wie neu, da ich es auch für andere TV-Aufnahme-SW nutzen will. Ich selber benutze TVHeadend anstelle von dem DVBService auf einen Linux-Maschine, aber die Internet-Oberfläche des TVHeadend hat nur einen recht geringen WAF. Am eigentlichen Fernseher wird Kodi verwendet. Der DVBViewer wird noch auf verschiedenen PCs genutzt, dass geht dann mittels Sat over IP, da der TVHeadend eine solche Schnittstelle als Server zur Verfügung stellt. Bin mit dem neuen Tool aber noch am Anfang.

Viele Grüße
     Stefan

**Comment by ghbw** [comment]
Hallo,

ich habe es jetzt eine Weile beobachtet. 
Deine Erklärung könnte plausibel sein.

Der Fehler wird jedoch auch gelegentlich geworfen, während oder kurz nach einer Senderdatenaktualisierung durch den TV-Browsers. 
Ich weiß nur nicht, wie ich dieses konkurrierende Verhalten verhindern kann, da die Aktualisierung der Senderdaten vom TV-Browser automatisch ausgeführt wird und entweder während des Herunterladdens oder direkt nach der Aktualisierung die Daten verarbeitet werden. Mit Verarbeitung meine ich, dass die Daten durch die Filter im Reiter Lieblingssender verarbeitet und dabei die hinterlegten Aktionen ausgeführt. In dem Fall die Weitergabe einer Sendung an das TimerImportTool zur Programmierung einer Sendung.
 
Viele Grüße

**Comment by GollmerSt** [comment]
Hallo,

gut, dann weiß ich in welche Richtung ich mir die Sache ansehen muss. Ich hatte damals einfach nicht dran gedacht. dass diese Updates vom TV-Browser asynchron erfolgen. Der TV-Browser ist eben eine Programmiermöglichkeit unter mehreren. Bei den andern stößt man über das Gui den Transfer an, der TV-Browser macht es selbsständig, das hatte ich nicht richtig durchdacht. Aber prinzipiell kann man dem Herr werden. Ich muss die Stellen durchgehen, wo es stören kann und das dann entsprechend synchronisieren.

Viele Grüße
   Stefan
